[package]
name = "parsable"
description = "A trait to easily parse data structures."
version = "0.1.4"
edition = "2018"
authors = [ "Sylvain Milan <milan.sylvain@gmail.com> "]
repository = "https://github.com/symil/parsable"
license = "MIT"

[dependencies]
parsable-macro = "0.1"
regex = "=1.5.6"
